services:
  app:
    build: .
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/titulyzer
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_SPEECH_API_KEY=${GOOGLE_SPEECH_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=titulyzer
    restart: unless-stopped

volumes:
  mongodb_data:
